version: "3.0"
services:
  py-rdb:
    image: py-rdb:latest
    build: 
      context: .
      args: 
        REVDEBUG_HOST_ARG: 20.199.127.147
